from youtube_upload.client import YoutubeUploader
import os


def upload_video(client_id, client_secret, access_token, refresh_token, title):
    '''client_id = "721095473760-gs7qp8etv8t2jaan2hostuqki1q00ude.apps.googleusercontent.com"
    client_secret = "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"

    access_token = "ya29.a0ARrdaM_Gu4K3J1oIZybAI5E0NmQ8Tb8CqZ-5I6XfpA13388zHJNornB1NWIqEXfuLJZbR_0HV31OYKxdLejSqjhXcfmZm_vrIKlSGSPYeW3iy8yv6dUe50WaLztQMxsY-f7qGMADfHAp-nr7zsVnMD665qrn"
    refresh_token = "1//0ghu1iICtaWqBCgYIARAAGBASNwF-L9Irh7nV_tudw_1vSESBGjOjcbI8kjuVsUyQrNHI2tp2zXmOGC0U9AY0hk9UrbSwBoSpjhk"'''

    uploader = YoutubeUploader(client_id, client_secret)

    uploader.authenticate(access_token=access_token,
                          refresh_token=refresh_token)

    options = {
        "title": title,  # The video title
        "description": "This is an autogenerated video.",  # The video description
        "tags": ["joke", "comedy", "dadjokes"],
        "categoryId": "22",
        # Video privacy. Can either be "public", "private", or "unlisted"
        "privacyStatus": "private",
        # Specifies if the Video if for kids or not. Defaults to False.
        "kids": False,
        # Optional. Specifies video thumbnail.
    }

    # upload video
    uploader.upload("video/video.mp4", options)

    uploader.close()
