from youtube_upload.client import YoutubeUploader
import os

client_id = os.getenv("CLIENT_ID")
client_secret = os.getenv("CLIENT_SECRET")

access_token = os.getenv("ACCESS_TOKEN")
refresh_token = os.getenv("REFRESH_TOKEN")
uploader = YoutubeUploader(client_id, client_secret)

uploader.authenticate(access_token=access_token, refresh_token=refresh_token)

options = {
    "title": "What do you tell a women with two black eyes?",  # The video title
    "description": "This is an autogenerated video.",  # The video description
    "tags": ["joke", "comedy", "dadjokes"],
    "categoryId": "22",
    # Video privacy. Can either be "public", "private", or "unlisted"
    "privacyStatus": "public",
    # Specifies if the Video if for kids or not. Defaults to False.
    "kids": False,
    # Optional. Specifies video thumbnail.
}

# upload video
uploader.upload("video/video.mp4", options)

uploader.close()
